### ISSUE TITLE
選択範囲のスタイル

### ISSUE THREAD

**Issue by nawawa** [nawawa/cansho-blog#11]
```css
::selection {
  background-color: rgba(var(--color-selection-rgb), 0.99);
}

::-moz-selection {
  background-color: rgba(var(--color-selection-rgb), 0.99);
}
```
